version: "3.8"
services:
  server:
    build: ./server
    env_file:
      - ./server/.env.example
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app # 개발 중 실시간 코드 반영 (옵션)
    command: npm run dev # 개발 모드: nodemon

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app # 개발 모드 실시간 반영
    command: npm run dev # App Router + Turbopack
